### ISSUE TITLE
[Research] NFV marketplace considerations

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#256] opened 2023-11-28 12:52 UTC
> Grab the Timestamp of the last collateral change or debt event, and require in the 721 allowance that it hasnt changed within 24 hours etc.

> Also a problem with EIP 6551

**Comment by daopunk** [comment] 2023-12-13 16:58
Duplicate of #277

**Closed by daopunk** 2023-12-13 16:58 UTC
Labels: ch-24
