### ISSUE TITLE
Wrap up #254 convert to RAD

### ISSUE THREAD

**Issue by pi0neerpat** [open-dollar/od-contracts#263] opened 2023-11-30 15:18 UTC
Complete remaining task for PR #254. This is blocking several other issues, so we need to prioritize this

> Before the value is sent to SafeEngine, we must convert from WAD to RAD

**Comment by 0xdavinchee** [comment] 2023-12-02 20:32
gm! I am not sure if the title of the issue is correct here, the issue is that the values are actually in RAD and we are using WAD functions on them and the issue is a possible overflow due to this.

## High-Level Overview

This issue is quite involved and is meant to address:
1. https://github.com/open-dollar/od-contracts/issues/214 (usage of `ONE_HUNDRED_WAD` instead of `WAD` for representing 100%)
2. https://github.com/open-dollar/od-contracts/issues/249 (decimal precision issues between `AccountingEngine` and `SAFEEngine`): SAFEEngine stores numbers at RAD precision, but calculations are being done assuming that these values are WAD values
3. https://github.com/open-dollar/od-contracts/issues/182 - broken AccountingEngine tests possibly due to the mismatch between the precision of what is stored in `AccountingEngine` vs. `SAFEEngine`

### 1. Use of `WAD` vs. `ONE_HUNDRED_WAD`

#### Issue Analysis

- 1. L214 checks `if (params.surplusTransferPercentage < ONE_HUNDRED_WAD)`, which will always return true because on L200 we check `if (_params.surplusTransferPercentage > WAD) revert AccEng_surplusTransferPercentOverLimit();`.
- 2. The use of `ONE_HUNDRED_WAD` leads to an inflated `_amountToSell` value (x100)

See the [audit results](https://github.com/code-423n4/2023-10-opendollar-findings/issues/26) for more details on the impact.

#### Proposed Solution

The submitter of the issue proposed to change `ONE_HUNDRED_WAD` to `WAD`, this seems like a straightforward and correct fix for this issue. It is clear that `WAD` is meant to represent 100% in the `auctionSurplus` function and not `ONE_HUNDRED_WAD` given the check on L200.

Using `WAD` instead of `ONE_HUNDRED_WAD` fixes both issues: the check will no longer always return true AND the `_amountToSell` value will not be inflated.

We can also cache the calculation done on L216.

### 2. Decimal precision issues

#### Issue Analysis

The main issue here is that wmul is supposed to multiply two uint256 WAD-precise numbers, however the `AccountingEngine` stores values in RAD.

Thus, `_coinBalance` and `_debtBalance` are RAD values, and we can assume `surplusAmount` and `surplusBuffer` to be RAD values if we look at the check on L209. We get further confirmation when we do a global search of `surplusAmount` in the codebase.

#### Proposed Solution(s)

st4rgarden proposed three solutions:

1. Revert changes back to previous state
- I am guessing this is out of the picture as this change was made quite explicitly to have this functionality.

2. Truncate the RAD balances to WAD (should only be `_params.surplusAmount`)
- We want to avoid truncating RAD balances to WAD otherwise we end up with precision loss.

3. Keep `_amountToSell` as `_params.surplusAmount` and instead calculate the transferSurplusPercentage as an additive amount. 
- I am not sure how this is meant to be implemented or how it is safer than the existing option. 
- `_params.surplusAmount` is the surplus amount to auction, and we calculate transferSurplusPercentage as an additive
- This implies that `_params.surplusAmount` is now the amount to sell on auction and the `_params.surplusTransferPercentage` is an amount which when multiplied against `_params.surplusAmount` should be equal to the expected amount to be transferred to the surplus receiver
- My confusion lies in the fact that we are still truncating with `toWad(surplusAmount)` and multiplying by `transferSurplusPercentage` (assuming this is a different value than `_params.surplusTransferPercentage`)
    - It seems we no longer divide by `WAD` (as done in `wmul`)
    - Is my assumption correct that `transferSurplusPercentage` is a modified value so that when multiplying it against `_params.surplusAmount` we actually get the desired value (e.g. 20% is 1.2x)? how is this done without dividing the percentage value (`0-WAD`) by `WAD` (e.g. 20%: amount * 2e17 / 1e18)?
        - If this is the case, this means we are truncating the percentage value - what happens if the surplus percentage amount is too small though, this would make `transferSurplusPercentage`

- Not sure what these two things means:

> he drawback here is that there has to be some special care taken to ensure that the total surplus amount is in correct excess of the surplusAmount + toRad((toWad(surplusAmount) * transferSurplusPercentage))

does this mean that the totalSurplusAmount is actually greater than `surplusAmount + toRad((toWad(surplusAmount) * transferSurplusPercentage))` (the surplusAmount, now amount to sell in auction + the additive transfer value)

> and that the accounting balances are updated in a way that is true to the original GEB system.

do you mean here that the accounting behavior should not change?

> Also there's another consideration which is that if surplusBuffer should always above the surplusAmount + toRad((toWad(surplusAmount) * transferSurplusPercentage)) then initiating an out of bounds surplus auction should not be possible.

cc @St4rgarden @pi0neerpat

**Closed** 2023-12-12 14:19 UTC
Labels: ch-24
