### ISSUE TITLE
Deploy test token contracts that are mintable to anyone and update params

### ISSUE THREAD

**Issue by cupOJoseph** [open-dollar/od-contracts#3] opened 2023-07-13 14:53 UTC
https://github.com/UseKeyp/opendollar/blob/dev/src/script/Params.s.sol

existing:
```
// Collateral Names
bytes32 constant RETH = bytes32('ETH-A'); // 0x4554482d41000000000000000000000000000000000000000000000000000000
bytes32 constant CETH = bytes32('WETH'); // 0x5745544800000000000000000000000000000000000000000000000000000000
bytes32 constant WSTETH = bytes32('WSTETH'); // 0x5753544554480000000000000000000000000000000000000000000000000000
bytes32 constant ARB = bytes32('OP'); // 0x4f50000000000000000000000000000000000000000000000000000000000000
bytes32 constant MAGIC = bytes32('WBTC'); // 0x5742544300000000000000000000000000000000000000000000000000000000
```

- a test token that always goes down in price

So for each of these that doesnt already exist a version should be deployed where we are testing that can be minted in unlimited amounts for testing: WSTETH, RETH, ARB instead of OP, WBTC.

Then add the tokens to the params with proper names and addresses in a few places as part of the deploy script

**Comment by pi0neerpat** [comment] 2023-09-20 17:43
Duplicate of #79

**Closed by pi0neerpat** 2023-09-20 17:43 UTC
Labels: ch-19
